parameters: {}
environment: {
  DATABASE_URL: ${MONGO_URI}
}
packages:
    - name: linkcreator
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: main
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}